### ISSUE TITLE
CUDA kernel error

### ISSUE THREAD

**Issue by dwgeneral** [chaojie/ComfyUI-MuseTalk#14]
```
Loads checkpoint by local backend from path: /root/ComfyUI/models/diffusers/TMElyralab/MuseTalk/dwpose/dw-ll_ucoco_384.pth
Traceback (most recent call last):
  File "/root/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/ComfyUI-MuseTalk/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "/root/ComfyUI/custom_nodes/ComfyUI-MuseTalk/nodes.py", line 26, in <module>
    from musetalk.utils.preprocessing import get_landmark_and_bbox,read_imgs,coord_placeholder
  File "/root/ComfyUI/custom_nodes/ComfyUI-MuseTalk/musetalk/utils/preprocessing.py", line 28, in <module>
    model = init_model(config_file, checkpoint_file, device=device)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/mmpose/apis/inference.py", line 129, in init_model
    model.to(device)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 208, in to
    return super().to(*args, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 844, in _apply
    self._buffers[key] = fn(buf)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Cannot import /root/ComfyUI/custom_nodes/ComfyUI-MuseTalk module for custom nodes: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by dwgeneral** [comment]
cuda: 11.7, torch: 2.0.1
