### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by samen168** [chaojie/ComfyUI-MuseTalk#18]
Traceback (most recent call last):
  File "H:\sd\sd-webui-aki-v4.5-comfy\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\sd\sd-webui-aki-v4.5-comfy\custom_nodes\ComfyUI-MuseTalk\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "H:\sd\sd-webui-aki-v4.5-comfy\custom_nodes\ComfyUI-MuseTalk\nodes.py", line 26, in <module>
    from musetalk.utils.preprocessing import get_landmark_and_bbox,read_imgs,coord_placeholder
  File "H:\sd\sd-webui-aki-v4.5-comfy/custom_nodes/ComfyUI-MuseTalk\musetalk\utils\preprocessing.py", line 28, in <module>
    model = init_model(config_file, checkpoint_file, device=device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmpose\apis\inference.py", line 103, in init_model
    model = build_pose_estimator(config.model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmpose\models\builder.py", line 35, in build_pose_estimator
    return POSE_ESTIMATORS.build(cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
          ^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmpose\models\pose_estimators\topdown.py", line 47, in __init__
    super().__init__(
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmpose\models\pose_estimators\base.py", line 47, in __init__
    self.backbone = MODELS.build(backbone)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmengine\registry\build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmengine\registry\registry.py", line 451, in get
    self.import_from_location()
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmengine\registry\registry.py", line 376, in import_from_location
    import_module(loc)
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmdet\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmdet\models\backbones\__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmdet\models\backbones\csp_darknet.py", line 11, in <module>
    from ..layers import CSPLayer
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmdet\models\layers\__init__.py", line 3, in <module>
    from .bbox_nms import fast_nms, multiclass_nms
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmdet\models\layers\bbox_nms.py", line 5, in <module>
    from mmcv.ops.nms import batched_nms
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
                 ^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by samen168** [comment]
Name: openmim
Version: 0.3.9
Summary: MIM Installs OpenMMLab packages
Home-page: https://github.com/open-mmlab/mim
Author: MIM Authors
Author-email: openmmlab@gmail.com
License:
Location: H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages
Requires: Click, colorama, model-index, opendatalab, pandas, pip, requests, rich, tabulate
Required-by:
---
Name: mmengine
Version: 0.10.4
Summary: Engine of OpenMMLab projects
Home-page: https://github.com/open-mmlab/mmengine
Author: MMEngine Authors
Author-email: openmmlab@gmail.com
License: UNKNOWN
Location: H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages
Requires: addict, matplotlib, numpy, opencv-python, pyyaml, regex, rich, termcolor, yapf
Required-by: mmcv
---
Name: mmcv
Version: 2.0.1
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Contributors
Author-email: openmmlab@gmail.com
License:
Location: H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages
Requires: addict, mmengine, numpy, opencv-python, packaging, Pillow, pyyaml, regex, yapf
Required-by:
---
Name: mmdet
Version: 3.1.0
Summary: OpenMMLab Detection Toolbox and Benchmark
Home-page: https://github.com/open-mmlab/mmdetection
Author: MMDetection Contributors
Author-email: openmmlab@gmail.com
License: Apache License 2.0
Location: H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages
Requires: matplotlib, numpy, pycocotools, scipy, shapely, six, terminaltables
Required-by:
---
Name: mmpose
Version: 1.1.0
Summary: OpenMMLab Pose Estimation Toolbox and Benchmark.
Home-page: https://github.com/open-mmlab/mmpose
Author: MMPose Contributors
Author-email: openmmlab@gmail.com
License: Apache License 2.0
Location: H:\sd\sd-webui-aki-v4.5-comfy\.ext\Lib\site-packages
Requires: chumpy, json-tricks, matplotlib, munkres, numpy, opencv-python, pillow, scipy, torchvision, xtcocotools
Required-by:

**Comment by samen168** [comment]
Torch 2.1.2 (CUDA 11.8)+ xFormers 0.0.23.post1

**Comment by samen168** [comment]
Problem fix after installing MuseV,
It seems that dependence is not complete

**Comment by DiamondsMe** [comment]
> 安装 MuseV 后的问题修复，似乎依赖不完整

how to install museV?comfyui node?
